services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${RUN_PORT:-8000}:8000"
    environment:
      - RUN_PORT=${RUN_PORT:-8000}
      - RUN_WORKERS=${RUN_WORKERS:-2}
      - DEBUG=${DEBUG:-True}
      
      - REQUESTS_URL=${REQUESTS_URL:-https://api.openai.com}
      - REQUESTS_MAX_RETRIES=${REQUESTS_MAX_RETRIES:-3}

      - HTTP_CLIENT_TIMEOUT=${HTTP_CLIENT_TIMEOUT:-300}
      - HTTP_CLIENTS_MAX_KEEPALIVE_CONNECTIONS=${HTTP_CLIENTS_MAX_KEEPALIVE_CONNECTIONS:-10}
    command: /app/start.sh
